apiVersion: v1
kind: Service
metadata:
  name: catalog
  namespace: catalog
spec:
  selector:
    app: catalog
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP